Revert "Default -t option to sh."
This reverts commit 097d364c22960ca27f3d7de310e722662d8b9325.

This commit broke -s output.

Conflicts:
	autorevision.asc

diff --git a/autorevision b/autorevision
--- a/autorevision
+++ b/autorevision
@@ -8,7 +8,6 @@
 # Config
 ARVERSION="1.0"
 TARGETFILE="/dev/stdout"
-AFILETYPE="sh"
 while getopts ":t:o:s:V" OPTION; do
 	case $OPTION in
 		t)
@@ -30,6 +29,15 @@ while getopts ":t:o:s:V" OPTION; do
 		;;
 	esac
 done
+
+if [[ ! -z "${VAROUT}"  ]] && [[ ! -z "${AFILETYPE}" ]]; then
+	echo "error: Improper argument combination." 1>&2
+	exit 1
+elif [[ -z "${VAROUT}"  ]] && [[ -z "${AFILETYPE}" ]]; then
+	echo "error: Improper argument combination." 1>&2
+	exit 1
+fi
+
 
 # Functions to extract data from different repo types.
 # For git repos
